'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Samples


	Public Partial Class QueryModificationDemo

		''' <summary>
		''' SqlEditor1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SqlEditor1 As Global.ActiveQueryBuilder.Web.WebForms.SqlEditor

		''' <summary>
		''' QueryBuilderControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected QueryBuilderControl1 As Global.ActiveQueryBuilder.Web.WebForms.QueryBuilderControl

		''' <summary>
		''' ObjectTreeView1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ObjectTreeView1 As Global.ActiveQueryBuilder.Web.WebForms.ObjectTreeView

		''' <summary>
		''' SubQueryNavigationBar1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SubQueryNavigationBar1 As Global.ActiveQueryBuilder.Web.WebForms.SubQueryNavigationBar

		''' <summary>
		''' Canvas1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Canvas1 As Global.ActiveQueryBuilder.Web.WebForms.Canvas

		''' <summary>
		''' StatusBar1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected StatusBar1 As Global.ActiveQueryBuilder.Web.WebForms.StatusBar

		''' <summary>
		''' Grid1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Grid1 As Global.ActiveQueryBuilder.Web.WebForms.Grid

		''' <summary>
		''' cbCustomers control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cbCustomers As Global.System.Web.UI.WebControls.CheckBox

		''' <summary>
		''' cbCompanyName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cbCompanyName As Global.System.Web.UI.WebControls.CheckBox

		''' <summary>
		''' tbCompanyName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected tbCompanyName As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cbOrders control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cbOrders As Global.System.Web.UI.WebControls.CheckBox

		''' <summary>
		''' cbOrderDate control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cbOrderDate As Global.System.Web.UI.WebControls.CheckBox

		''' <summary>
		''' tbOrderDate control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected tbOrderDate As Global.System.Web.UI.WebControls.TextBox
	End Class
End Namespace
