'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Samples


	Public Partial Class QueryResultsDemo

		''' <summary>
		''' QueryBuilderControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected QueryBuilderControl1 As Global.ActiveQueryBuilder.Web.WebForms.QueryBuilderControl

		''' <summary>
		''' ObjectTreeView1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ObjectTreeView1 As Global.ActiveQueryBuilder.Web.WebForms.ObjectTreeView

		''' <summary>
		''' SubQueryNavigationBar1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SubQueryNavigationBar1 As Global.ActiveQueryBuilder.Web.WebForms.SubQueryNavigationBar

		''' <summary>
		''' Canvas1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Canvas1 As Global.ActiveQueryBuilder.Web.WebForms.Canvas

		''' <summary>
		''' StatusBar1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected StatusBar1 As Global.ActiveQueryBuilder.Web.WebForms.StatusBar

		''' <summary>
		''' Grid1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Grid1 As Global.ActiveQueryBuilder.Web.WebForms.Grid

		''' <summary>
		''' SqlEditor1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SqlEditor1 As Global.ActiveQueryBuilder.Web.WebForms.SqlEditor

		''' <summary>
		''' CriteriaBuilder1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected CriteriaBuilder1 As Global.ActiveQueryBuilder.Web.WebForms.CriteriaBuilder
	End Class
End Namespace
