'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Samples
    
    Partial Public Class SaveAndLoadUserQueries
        
        '''<summary>
        '''QueryBuilderControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents QueryBuilderControl1 As Global.ActiveQueryBuilder.Web.WebForms.QueryBuilderControl
        
        '''<summary>
        '''ObjectTreeView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjectTreeView1 As Global.ActiveQueryBuilder.Web.WebForms.ObjectTreeView
        
        '''<summary>
        '''SubQueryNavigationBar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubQueryNavigationBar1 As Global.ActiveQueryBuilder.Web.WebForms.SubQueryNavigationBar
        
        '''<summary>
        '''Canvas1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Canvas1 As Global.ActiveQueryBuilder.Web.WebForms.Canvas
        
        '''<summary>
        '''StatusBar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusBar1 As Global.ActiveQueryBuilder.Web.WebForms.StatusBar
        
        '''<summary>
        '''Grid1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Grid1 As Global.ActiveQueryBuilder.Web.WebForms.Grid
        
        '''<summary>
        '''SqlEditor1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlEditor1 As Global.ActiveQueryBuilder.Web.WebForms.SqlEditor
    End Class
End Namespace
